### ISSUE TITLE
Problems with installing bash shell 

### ISSUE THREAD

**Issue by Mococoa22** [maxheld83/fossos#56]
Hi. This was a homework for #17 .
I don't know how to install the bash shell for mac. 
(I am using macbook air.)
It would be very helpful if someone could tell me how to. Thanks.

**Comment by maxheld83** [comment]
You're in luck @Mococoa22 – macOS ships with a bash shell, so there is nothing to install.
Just open "Terminal", and you got it.

Also says so at https://www.maxheld.de/fossos/stack.html#command_line_interface 😏 

Going to close this then.
