### ISSUE TITLE
Problem : Package Manager not having Atom Text Editor 

### ISSUE THREAD

**Issue by Mococoa22** [maxheld83/fossos#57]
Not knowing anything, I installed my package manager (homebrew ) and found that there is no package of _atom text editor_ here.
So I couldn't install it.
And it looks like one should install only one package manager.
Now I don't know what to do. Should I download the **atom** as a file?

**Comment by maxheld83** [comment]
you're right that you cannot install atom via homebrew.

As I said on the website:

> Consider installing the below software via your package manager. Whether this is advisable or even possible for any given piece of software depends on the software and your operating system. Google around for advice. As a rule of thumb, “heavy” packages (such as LaTeX) are sometimes best installed “by hand”.

So yes, you can just download atom by hand  from https://atom.io

Incidentally, atom also has its own updating mechanism, so there would be very little advantage of doing this via homebrew.
